### ISSUE TITLE
Validation for register and login pages

### ISSUE THREAD

**Issue by andjey** [andjey/travel-around#8]

**Comment by CapitainBlack** [comment]
Validation from client side is already added. Close issue after you part of work :)

**Comment by andjey** [comment]
Added register validation. Login is without validation

**Comment by andjey** [comment]
But i forgot to add password confirmation check, so i am not closing this issue now

**Comment by CapitainBlack** [comment]
On login page there is validation on server side if user missed to enter login name or password.

**Comment by andjey** [comment]
Done!
