### ISSUE TITLE
Fix bug related with footer on our layouts.

### ISSUE THREAD

**Issue by CapitainBlack** [andjey/travel-around#9]
You all already know)

**Comment by CapitainBlack** [comment]
![222](https://cloud.githubusercontent.com/assets/10583517/7564761/8ae1284a-f7f2-11e4-81a2-0b820206c035.JPG)
![111](https://cloud.githubusercontent.com/assets/10583517/7564762/8af681ae-f7f2-11e4-8887-9c862640d5c8.JPG)

**Comment by CapitainBlack** [comment]
try to fix this until i'm doing another stuffs

**Comment by CapitainBlack** [comment]
I already made dynamic changes of layout if user is logined or not.

**Comment by andjey** [comment]
Done!
